<a href="https://colab.research.google.com/github/jonathanherber/python_data_science/blob/main/Alura_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

In [9]:
anos = np.loadtxt('carros-anos.txt',dtype=int)

In [ ]:
anos

In [11]:
km_media = km / (2022-anos)

In [ ]:
km_media

In [ ]:
type(km_media)

In [ ]:
np.arange(10)

In [19]:
var = np.array([1,2,3,4])

In [ ]:
var.dtype

In [ ]:
var.shape

In [27]:
lista = [[4,3,2,1,1], [5,6,7,8,9]]

In [28]:
num = np.array(lista)

In [ ]:
num

In [ ]:
num.shape

In [31]:
np_array = np.arange(1000000)

In [32]:
py_list = list(range(1000000))

In [34]:
%time for _ in range(100): np_array * 2   #importante se atentar o tempo de execucao de numpy em relacao ao list padrao do python

CPU times: user 112 ms, sys: 2.39 ms, total: 114 ms
Wall time: 118 ms


In [35]:
%time for _ in range(100): py_pylist = [x * 2 for x in py_list] 

CPU times: user 8.55 s, sys: 2.01 s, total: 10.6 s
Wall time: 10.6 s


In [36]:
km = [44123,6363,31293,0., 13891]
anos = [2003,1990,2010, 2007,2010]

In [ ]:
idade = 2019 - anos   #no list do python precisa do for

In [41]:
km = np.array([44123,6363,31293,0., 13891])
anos = np.array([2003,1990,2010, 2007,2010])

In [42]:
idade = 2019 - anos   #no numpy podemos fazer a operacao

In [ ]:
idade

In [44]:
contador = np.arange(10)

In [45]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [47]:
contador[contador>5] 

array([6, 7, 8, 9])